---
swagger: "2.0"
info:
  description: "This is ElectraPay API"
  version: "1.0.0"
  title: "ElectraPay"
  contact:
    email: "dev@electraproject.org"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/electraproject/ElectraPay/1.0.0"
tags:
- name: "account"
  description: "Secured Merchant account only calls"
schemes:
- "https"
paths:
  /account:
    get:
      tags:
      - "account"
      summary: "Fetch account details"
      description: "No parameters"
      operationId: "getAccount"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/account"
        400:
          description: "Invalid request"
        401:
          description: "Authorization information is missing or invalid."
        404:
          description: "Account information not found."
        500:
          description: "Internal service error"
      x-swagger-router-controller: "Account"
    put:
      tags:
      - "account"
      summary: "Add a new account"
      description: "Add a new account."
      operationId: "add"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/account"
        400:
          description: "Invalid request"
        401:
          description: "Authorization information is missing or invalid."
        404:
          description: "Account information not found."
        500:
          description: "Internal service error"
      x-swagger-router-controller: "Account"
securityDefinitions:
  basicAuth:
    type: "basic"
  apiKey:
    type: "apiKey"
    name: "X-Auth-Token"
    in: "header"
definitions:
  account:
    type: "object"
    required:
    - "currency"
    - "defaultvat"
    - "description"
    - "id"
    - "language"
    - "name"
    - "organisation"
    - "status"
    - "timezone"
    - "type"
    - "walletaddress"
    properties:
      id:
        type: "string"
        format: "uuid"
        example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        description: "Unique id assigned by electraPay"
      name:
        type: "string"
        example: "Electra Donation Wallet"
        description: "Account name"
      description:
        type: "string"
        example: "Electra Donation Wallet"
        description: "Account description"
      logo:
        type: "string"
        example: "http://electraproject.org/images/logo.svg"
        description: "Account logo URL"
      address1:
        type: "string"
        description: "Account address line 1"
      address2:
        type: "string"
        description: "Account address line 2"
      postalcode:
        type: "string"
        example: "2390"
        description: "Account postal code"
      city:
        type: "string"
        example: "Amsterdam"
        description: "Account city"
      country:
        type: "string"
        example: "NL"
        description: "Account country in [ISO 3166-1 alpha-2] (https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)"
      language:
        type: "string"
        example: "nl"
        description: "Account language [ISO 639-1] (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)"
      timezone:
        type: "string"
        example: "Europe/Amsterdam"
        description: "Timezone full description on [[Wikipedia] (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)"
      callbackuri:
        type: "string"
        example: "https://www.electrabay/api"
        description: "Callback URI"
      website:
        type: "string"
        example: "https://www.electrabay"
        description: "Website address"
      type:
        type: "string"
        example: "nonprofit"
        description: "Account type"
        enum:
        - "personal"
        - "business"
        - "nonprofit"
      currency:
        type: "array"
        example:
        - "USD"
        description: "List of allowed currencies"
        items:
          $ref: "#/definitions/currency"
      walletaddress:
        type: "string"
        example: "EVggmyfsA7krt7XsCYyh5DVe5JxDbVs5cZ"
        description: "ECA wallet address"
      contactname:
        type: "string"
        example: "Mr E Peterson"
        description: "Name of contact person"
      email:
        type: "string"
        format: "email"
        example: "support@electrabay.com"
        description: "email address"
      phone:
        type: "string"
        example: "+44 333 333 333"
        description: "phone number"
      vatno:
        type: "string"
        example: "140976"
        description: "VAT number"
      defaultvat:
        type: "number"
        example: 25
        description: "VAT percentage"
        minimum: 0
        maximum: 100
      organisation:
        type: "string"
        example: "ElectraProject"
        description: "Name from Organisation Model"
      plugintype:
        type: "object"
        example: "MAGENTO2"
        description: "eCommerce Plugin list"
        properties: {}
      status:
        type: "string"
        example: "ACTIVE"
        description: "The account status"
        enum:
        - "ACTIVE"
        - "SUSPENDED"
        - "SUSPECT"
    example:
      country: "NL"
      website: "https://www.electrabay"
      address2: "address2"
      city: "Amsterdam"
      address1: "address1"
      timezone: "Europe/Amsterdam"
      vatno: "140976"
      description: "Electra Donation Wallet"
      organisation: "ElectraProject"
      language: "nl"
      type: "nonprofit"
      contactname: "Mr E Peterson"
      plugintype: "MAGENTO2"
      walletaddress: "EVggmyfsA7krt7XsCYyh5DVe5JxDbVs5cZ"
      phone: "+44 333 333 333"
      postalcode: "2390"
      callbackuri: "https://www.electrabay/api"
      name: "Electra Donation Wallet"
      logo: "http://electraproject.org/images/logo.svg"
      currency:
      - "USD"
      id: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      defaultvat: 25
      email: "support@electrabay.com"
      status: "ACTIVE"
  key:
    type: "object"
    required:
    - "created"
    - "key"
    properties:
      key:
        type: "string"
        example: "priv_fcfac2016614418f969fa5697383e47c"
        description: "Api key"
      created:
        type: "string"
        format: "date-time"
        example: "2018-04-04T12:40:56.656+00:00"
        description: "Key creation date. In [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601)\
          \ extended offset date-time format."
  transaction:
    type: "object"
    required:
    - "accountid"
    - "id"
    - "longdescription"
    - "shortdescription"
    properties:
      id:
        type: "string"
        format: "uuid"
        example: "f341d1ac-5b05-9c21-98f2-a91578b1245"
        description: "Unique id assigned by electraPay"
      accountid:
        type: "string"
        example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        description: "Account id assigned by ElectraPay"
      shortdescription:
        type: "string"
        example: "Electra donation"
        description: "A short description of what is being paid for."
      longdescription:
        type: "string"
        example: "Electra donation to developers"
        description: "A long description of what is being paid for."
      amount:
        type: "number"
        format: "float"
        example: 200.0
        description: "The order amount (excluding fees)"
      currency:
        $ref: "#/definitions/currency"
      fee:
        type: "string"
        example: "200.0"
        description: "Fee structure"
      paymentmethod:
        $ref: "#/definitions/paymentmethod"
      paymenttype:
        type: "string"
        example: "donation"
        description: "The payment type"
        enum:
        - "goods"
        - "services"
        - "donation"
        - "event"
        - "personal"
      expirytime:
        type: "string"
        example: "USD"
        description: "The currency of the charged amount"
  paymentmethod:
    type: "object"
    properties:
      id:
        type: "integer"
      paymentmethodtype:
        type: "object"
        properties: {}
      walletaddress:
        type: "string"
      exchangerate:
        type: "number"
        format: "float"
      amount:
        type: "number"
        format: "float"
      fee:
        type: "array"
        items:
          type: "string"
    description: "Payment method object"
    example: "ee1"
  currency:
    type: "object"
    description: "Currency list"
    example: "USD"
    enum:
    - "USD"
    - "EURO"
