---
swagger: "2.0"
info:
  description: "REST API for ElectraPay"
  version: "1.0.0"
  title: "ElectraPay API"
  contact:
    email: "develop@electraproject.org"
host: "virtserver.swaggerhub.com"
basePath: "/electraproject/ElectraPay/1.0.0"
tags:
- name: "account"
  description: "Secured Merchant account only calls"
- name: "order"
  description: "Secured Merchant order only calls"
schemes:
- "https"
paths:
  /v1/account/{id}:
    get:
      tags:
      - "account"
      summary: "Fetch account details"
      description: "Retrieve the account details."
      operationId: "getAccount"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "Enter the accountid to retrieve"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/account"
        400:
          description: "Invalid request"
        401:
          description: "Authorization information is missing or invalid."
        404:
          description: "Account information not found."
        500:
          description: "Internal service error"
      security:
      - basicAuth: []
      x-swagger-router-controller: "Account"
  /v1/account:
    post:
      tags:
      - "account"
      summary: "Add a new account"
      description: "Add a new account."
      operationId: "accountNew"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters: []
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/account"
        400:
          description: "Invalid request"
        401:
          description: "Authorization information is missing or invalid."
        404:
          description: "Account information not found."
        500:
          description: "Internal service error"
      x-swagger-router-controller: "Account"
  /v1/order:
    post:
      tags:
      - "order"
      summary: "Add a new order request"
      description: "Process a new order request"
      operationId: "orderNew"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "order"
        description: "New order details"
        required: true
        schema:
          $ref: "#/definitions/ordernew"
      responses:
        200:
          description: "Successful"
          schema:
            $ref: "#/definitions/order"
        400:
          description: "Invalid request"
        401:
          description: "Authorization information is missing or invalid."
        404:
          description: "Account information not found."
        500:
          description: "Internal service error"
      x-swagger-router-controller: "Order"
securityDefinitions:
  basicAuth:
    type: "basic"
  apiKey:
    type: "apiKey"
    name: "X-Auth-Token"
    in: "header"
definitions:
  account:
    type: "object"
    required:
    - "accounttype"
    - "currencies"
    - "defaultvat"
    - "description"
    - "id"
    - "language"
    - "name"
    - "organisation"
    - "plugintype"
    - "status"
    - "timezone"
    - "uuid"
    - "walletaddress"
    - "walletcurrency"
    properties:
      id:
        type: "number"
        example: 1
        description: "Internal id assigned by electraPay"
      uuid:
        type: "string"
        format: "uuid"
        example: "d290f1ee-6c54-4b01-90e6-d701748f0851"
        description: "Unique id assigned by electraPay"
      name:
        type: "string"
        example: "Electra Donation Wallet"
        description: "Account name"
      description:
        type: "string"
        example: "Electra Donation Wallet"
        description: "Account description"
      accounttype:
        type: "string"
        example: "nonprofit"
        description: "Account type"
        enum:
        - "personal"
        - "business"
        - "nonprofit"
      logourl:
        type: "string"
        example: "http://electraproject.org/images/logo.svg"
        description: "Account logo URL"
      logoimg:
        type: "string"
        example: "http://electraproject.org/images/logo.svg"
        description: "Account logo URL"
      address1:
        type: "string"
        description: "Account address line 1"
      address2:
        type: "string"
        description: "Account address line 2"
      address3:
        type: "string"
        description: "Account address line 3"
      postalcode:
        type: "number"
        example: 2390
        description: "Account postal code"
      suburb:
        type: "string"
        example: "Leidseplein"
        description: "Account Suburb name"
      city:
        type: "string"
        example: "Amsterdam"
        description: "Account city"
      country:
        type: "string"
        example: "NL"
        description: "Account country in [ISO 3166-1 alpha-2] (https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)"
      language:
        type: "string"
        example: "nl"
        description: "Account language [ISO 639-1] (https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes)"
      timezone:
        type: "string"
        example: "Europe/Amsterdam"
        description: "Timezone full description on [[Wikipedia] (https://en.wikipedia.org/wiki/List_of_tz_database_time_zones)"
      callbackuri:
        type: "string"
        example: "https://www.electrabay/api"
        description: "Callback URI"
      website:
        type: "string"
        example: "https://www.electrabay"
        description: "Website address"
      currencies:
        type: "array"
        example:
        - "USD"
        description: "List of allowed currencies"
        items:
          $ref: "#/definitions/currency"
      walletaddress:
        type: "string"
        example: "EVggmyfsA7krt7XsCYyh5DVe5JxDbVs5cZ"
        description: "Coin wallet address"
      walletcurrency:
        type: "string"
        example: "ECA"
        description: "Name of coin"
      contacttitle:
        type: "string"
        example: "Mr"
        description: "Title contact person"
      contactfirstname:
        type: "string"
        example: "Edward"
        description: "Firstname of contact person"
      contactmiddlenames:
        type: "string"
        example: "Mark"
        description: "Middlenames of contact person"
      contactlastname:
        type: "string"
        example: "Peterson"
        description: "Lastname of contact person"
      contactemail:
        type: "string"
        format: "email"
        example: "edwardp@electrabay.com"
        description: "email address of contact person"
      contactphone:
        type: "string"
        example: "+44 333 333 333"
        description: "phone number of contact person"
      contactmobile:
        type: "string"
        example: "+44 333 333 333"
        description: "mobile number of contact person"
      vatno:
        type: "string"
        example: "V140976"
        description: "VAT number"
      defaultvat:
        type: "number"
        example: 25
        description: "VAT percentage"
        minimum: 0
        maximum: 100
      organisation:
        type: "string"
        example: "ElectraProject"
        description: "Name from Organisation Model"
      plugintype:
        type: "string"
        example: "MAGENTO2"
        description: "eCommerce Plugin list"
        enum:
        - "MAGENTO2"
        - "MAGENTO"
        - "SHOPIFY"
      status:
        type: "string"
        example: "ACTIVE"
        description: "The account status"
        enum:
        - "ACTIVE"
        - "SUSPENDED"
        - "SUSPECT"
        - "PENDING"
        - "DEACTIVATED"
    example:
      contactemail: "edwardp@electrabay.com"
      country: "NL"
      city: "Amsterdam"
      timezone: "Europe/Amsterdam"
      vatno: "V140976"
      accounttype: "nonprofit"
      description: "Electra Donation Wallet"
      organisation: "ElectraProject"
      language: "nl"
      uuid: "d290f1ee-6c54-4b01-90e6-d701748f0851"
      logourl: "http://electraproject.org/images/logo.svg"
      plugintype: "MAGENTO2"
      logoimg: "http://electraproject.org/images/logo.svg"
      walletaddress: "EVggmyfsA7krt7XsCYyh5DVe5JxDbVs5cZ"
      postalcode: 2390
      id: 1
      contactphone: "+44 333 333 333"
      contactmobile: "+44 333 333 333"
      website: "https://www.electrabay"
      contactfirstname: "Edward"
      address3: "address3"
      address2: "address2"
      address1: "address1"
      contactlastname: "Peterson"
      callbackuri: "https://www.electrabay/api"
      contacttitle: "Mr"
      contactmiddlenames: "Mark"
      name: "Electra Donation Wallet"
      suburb: "Leidseplein"
      walletcurrency: "ECA"
      defaultvat: 25
      currencies:
      - "USD"
      status: "ACTIVE"
  key:
    type: "object"
    required:
    - "created"
    - "key"
    properties:
      key:
        type: "string"
        example: "priv_fcfac2016614418f969fa5697383e47c"
        description: "Api key"
      created:
        type: "string"
        format: "date-time"
        example: "2018-04-04T12:40:56.656+00:00"
        description: "Key creation date. In [ISO-8601](http://en.wikipedia.org/wiki/ISO_8601)\
          \ extended offset date-time format."
  order:
    type: "object"
    required:
    - "accountid"
    - "id"
    - "longdescription"
    - "orderamount"
    - "ordercurrency"
    - "paymentcategory"
    - "reference"
    - "shortdescription"
    - "uuid"
    properties:
      id:
        type: "number"
        example: 1
        description: "Unique id assigned by electraPay"
      uuid:
        type: "string"
        format: "uuid"
        example: "f59f2257-3363-4f2f-a8a4-a288b7c0b7db"
        description: "Unique id assigned by electraPay"
      accountid:
        type: "number"
        example: 1
        description: "Account id assigned by ElectraPay"
      shortdescription:
        type: "string"
        example: "Electra donation"
        description: "A short description of what is being paid for."
      longdescription:
        type: "string"
        example: "Electra donation to developers"
        description: "A long description of what is being paid for."
      reference:
        type: "string"
        example: "ORD-11109"
        description: "Unique reference to link to calling system."
      paymentcategory:
        type: "string"
        example: "donation"
        description: "The payment type"
        enum:
        - "goods"
        - "services"
        - "donation"
        - "event"
        - "personal"
      ordercurrency:
        type: "string"
        example: "USD"
        description: "The currency of the order"
        enum:
        - "ECA"
        - "BTC"
        - "USD"
      orderamount:
        type: "number"
        format: "float"
        example: 12.0
        description: "The order amount (excluding fees)"
      quotecurrency:
        type: "string"
        example: "ECA"
        description: "The currency of the quoted amount"
        enum:
        - "ECA"
      quoteamount:
        type: "number"
        format: "float"
        example: 20000.0
        description: "The final quoted amount"
      qrcode:
        type: "string"
        example: "null"
        description: "Base64 image for the QR Code"
      ordertoken:
        type: "number"
        example: 11654
        description: "A random generated token number that can also be used for payment."
      ordertransactionid:
        type: "string"
        example: "null"
        description: "Blockchain transactionid for the final payment"
      orderstatus:
        type: "string"
        enum:
        - "PENDING"
        - "AWAITING_PAYMENT"
        - "FINAL_PAYMENT"
        - "CLOSED"
        - "CANCELLED"
        - "REVERSED"
    example:
      shortdescription: "Electra donation"
      paymentcategory: "donation"
      orderstatus: "PENDING"
      qrcode: "null"
      ordertransactionid: "null"
      uuid: "f59f2257-3363-4f2f-a8a4-a288b7c0b7db"
      quotecurrency: "ECA"
      reference: "ORD-11109"
      ordertoken: 11654
      accountid: 1
      quoteamount: 20000.0
      orderamount: 12.0
      longdescription: "Electra donation to developers"
      id: 1
      ordercurrency: "USD"
  ordernew:
    type: "object"
    required:
    - "accountid"
    - "longdescription"
    - "orderamount"
    - "ordercurrency"
    - "paymentcategory"
    - "reference"
    - "shortdescription"
    properties:
      accountid:
        type: "number"
        example: 1
        description: "Account id assigned by ElectraPay"
      shortdescription:
        type: "string"
        example: "Electra donation"
        description: "A short description of what is being paid for"
      longdescription:
        type: "string"
        example: "Electra donation to developers"
        description: "A long description of what is being paid for"
      reference:
        type: "string"
        example: "ORD-11109"
        description: "Unique reference to link to calling system."
      paymentcategory:
        type: "string"
        example: "donation"
        description: "The payment type"
        enum:
        - "goods"
        - "services"
        - "donation"
        - "event"
        - "personal"
      ordercurrency:
        type: "string"
        example: "USD"
        description: "The currency of the order"
        enum:
        - "ECA"
        - "BTC"
        - "USD"
      orderamount:
        type: "number"
        format: "float"
        example: 12.0
        description: "The order amount (excluding fees)"
  currency:
    type: "string"
    description: "Currency list"
    example: "USD"
    enum:
    - "USD"
    - "EUR"
